services:
  - type: web
    name: DevToolsSuit
    env: docker
    plan: free
    buildCommand: "dotnet publish -c Release -o out"
    startCommand: "dotnet out/DevToolsSuit.dll"
    envVars:
      - key: ASPNETCORE_URLS
        value: "http://*:10000"
